import Head from 'next/head'
import { useEffect, useState } from 'react'
import {motion} from 'framer-motion'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Landing from '../components/Landing'
import Works from '../components/Works'
import useLenisScroll from '../hooks/useLenisScroll'
import Menu from '../components/Menu'
import {FiArrowUpRight} from 'react-icons/fi'

export default function Home() {

  useLenisScroll()

  
  const [isMenuOpen, setIsMenuOpen] = useState(false)

  
  
  

  

  return (
    <>
      <Head>
        <title>THEINFINITYEDGE | CREATIVE ARTIST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <Menu isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen} />
      <div>
        <Header  setIsMenuOpen={setIsMenuOpen}/>
        <Landing />
      </div>
      <div  >
        <Works />
        <Footer/>
      </div>
    </>
  )
}
