import Head from 'next/head'
import { useEffect, useState } from 'react'
import {motion} from 'framer-motion'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Landing from '../components/Landing'
import Works from '../components/Works'
import useLenisScroll from '../hooks/useLenisScroll'
import Menu from '../components/Menu'
import {FiArrowUpRight} from 'react-icons/fi'

export default function Home() {

  useLenisScroll()

  const [mousePosition, setMousePosition] = useState({
    x:0,
    y:0
  })
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [cursorVariant,setCursorVariant] = useState("default")
  const [imageHover,setImageHover] = useState(false)
  const [mailHover,setMailHover] = useState(false)

  useEffect(() => {

    const mouseMove = (e) => {
      const cursor = document.querySelector(".cursor")
      setMousePosition({
        x:e.clientX - 25 + "px",
        y:e.clientY - 25 + "px"
      })
      cursor.style.transform = `translate(${mousePosition.x},${mousePosition.y})`
    }
    window.addEventListener('mousemove',mouseMove)

    return () => {
      window.removeEventListener("mousemove",mouseMove)
    }
  }, [mousePosition])
  
  const variants = {
    default:{
      backgroundColor:"black"
    },

    text:{
      height:80,
      width:80,
    },
    section:{
      backgroundColor:"white"
    },
    menu:{
      backgroundColor:"white",
      height:100,
      width:100,
    },
    image:{
      backgroundColor:"white",
      height:100,
      width:100,
    },
    big:{
      backgroundColor:"white",
      height:100,
      width:100,
    },
    mail:{
      backgroundColor:"white",
      height:100,
      width:100,
    }
  }

  const cursorEnterText = () => {
    setCursorVariant("section")
  }
  const cursorLeaveText = () => {
    setCursorVariant("default")
  }

  return (
    <>
      <Head>
        <title>THEINFINITYEDGE | CREATIVE ARTIST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <motion.div className={`cursor arial ${imageHover || cursorVariant==="mail" ? 'mix-blend-normal' : 'mix-blend-difference'} flex justify-center items-center arial `}
          variants = {variants}
          animate  = {cursorVariant}
      >
        {cursorVariant==="image" ? (
          <FiArrowUpRight  size={30} className={'font-light'}/>
        ) : null}
        {cursorVariant==="mail" ? (
          'Contact'
        ) : null}
      </motion.div>
      <Header setCursorVariant={setCursorVariant} setIsMenuOpen={setIsMenuOpen}/>
      <Menu isMenuOpen={isMenuOpen} setIsMenuOpen={setIsMenuOpen} setCursorVariant={setCursorVariant}/>
      <Landing setCursorVariant={setCursorVariant}/>
      <div onMouseEnter={() => cursorEnterText()} onMouseLeave={() => cursorLeaveText()}>
        <Works setImageHover={setImageHover} setCursorVariant={setCursorVariant}/>
        <Footer setCursorVariant={setCursorVariant} setMailHover={setMailHover}/>
      </div>
    </>
  )
}
